### ISSUE TITLE
Exceptions during parallel decode of v2

### ISSUE THREAD

**Issue by robobario** [InteractiveAdvertisingBureau/iabtcf-java#115]
Hi :wave: ,

We are using version 2.0.7 to decode version 2 consent strings and seeing intermittent exceptions like:

```
com.iabtcf.exceptions.ByteParseException: read 2 bytes at index 4295 out of bounds for buffer length 1257
	at com.iabtcf.utils.BitReader.ensureReadable(BitReader.java:75)
	at com.iabtcf.utils.BitReader.readBits12(BitReader.java:225)
	at com.iabtcf.decoder.TCStringV2.fillPublisherRestrictions(TCStringV2.java:220)
	at com.iabtcf.decoder.TCStringV2.getPublisherRestrictions(TCStringV2.java:416)
	at com.iabtcf.decoder.TCStringV2.hashCode(TCStringV2.java:512)
        ... 
```

The same consent strings decode if we retry the decode/hashCode call (we're using the lazy decode option). So we suspect a thread safety issue. I've made a [unit test that fails intermittently](https://gist.github.com/robobario/25717683e361328caac9aff99616b2e1) with the same kind of exceptions and also ones like:

```
Caused by: com.iabtcf.exceptions.InvalidRangeFieldException: start vendor id (60513) is greater than endVendorId (33825)
	at com.iabtcf.decoder.TCStringV2.vendorIdsFromRange(TCStringV2.java:188)
	at com.iabtcf.decoder.TCStringV2.fillPublisherRestrictions(TCStringV2.java:232)
	at com.iabtcf.decoder.TCStringV2.getPublisherRestrictions(TCStringV2.java:416)
```

One bit of code I'm interested in is [here](https://github.com/InteractiveAdvertisingBureau/iabtcf-java/blob/7ee75c0ce3176860b4cb4b5ffe914adba1b238bd/iabtcf-decoder/src/main/java/com/iabtcf/utils/FieldDefs.java#L251) for an `isDynamicPvt() == true` field, could another thread set `value` between `value = doCompute(t);` and `return value;` and cause an offset for another decode to be returned?

Thanks
Rob

**Comment by philipphoffmann** [comment]
We just stumbled across the same problem today and are currently trying to find the root cause.

**Comment by laktech** [comment]
Thanks for reporting this issue! This is definitely a bug.

The root cause is in initializing the com.iabtcf.utils.FieldDefs enum.  Specifically, in places when isDynamicPvt() is evaluated for the frist time which is done [here](https://github.com/InteractiveAdvertisingBureau/iabtcf-java/blob/7ee75c0ce3176860b4cb4b5ffe914adba1b238bd/iabtcf-decoder/src/main/java/com/iabtcf/utils/FieldDefs.java#L2603).

For fields that follow a dynamic field, at runtime we statically set that all subsequent fields are "dynamic" -- that is, it'll require reading the length or offset of a previous field in order to determine it's length or offset.

Unfortunately, the code is implemented as,

```
         private boolean isDynamicPvt() {
             if (!dynamicInitialized) {
                dynamicInitialized = true;
                 isDynamic = isDynamic();
             }
```

It's therefore possible that one thread sets `dynamicInitialized` to true before it actually determines the value of `isDynamic`.

A workaround would be to force the evaluation of these dynamic fields in a single thread. This would require you to decode a string from a single thread. I'll submit a PR shortly.

**Comment by laktech** [comment]
@robobario your intuition was spot on. The issue was with returning a 'value' that was computed by a different thread. I went through and made sure that the FieldDef code was made thread-safe. You should now be able to decode strings from multiple threads.

**Comment by robobario** [comment]
Thanks for the quick fix
