### ISSUE TITLE
OOBVendorsEncoder fails (NoSuchElementException) with TC String having empty OOB section

### ISSUE THREAD

**Issue by a-s-rose** [InteractiveAdvertisingBureau/iabtcf-java#2]
Using the following TC String: `COrAPwwOrAPwwCnABAENAECAAP_AAAAAAAAAFXQCgAJQAYAA1ACCAGIAQIAmQBrgDggK8Ar4BpgDfgH2AQIAmSBSAFIgKZAVIAqwBVwAAAAA.IAAA.QAAA.YAAAAAAAAA`

And the following testcode:
```java
public class IabLibTest {

    private String base64TcString = "COrAPwwOrAPwwCnABAENAECAAP_AAAAAAAAAFXQCgAJQAYAA1ACCAGIAQIAmQBrgDggK8Ar4BpgDfgH2AQIAmSBSAFIgKZAVIAqwBVwAAAAA.IAAA.QAAA.YAAAAAAAAA";

    @Test
    public void readTcString() {
        TCString tcString = TCString.getInstance();
        final TCModel tcModel = tcString.decode(base64TcString);
        System.out.println(tcModel);
    }
}
```

the test fails throwing the following exception:
```
java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1327)
	at java.util.TreeMap.firstKey(TreeMap.java:290)
	at java.util.TreeSet.first(TreeSet.java:394)
	at com.iabtcf.gdpr.phase2.encoder.segment.OOBVendorsEncoder.decode(OOBVendorsEncoder.java:47)
	at com.iabtcf.gdpr.phase2.Utils.TCString.decode(TCString.java:62)
```
This is because at OOBVendorsEncoder.java:47 the vector object has no elements and calling .first() fails.

**Comment by abhinandanjvx** [comment]
Yeah. Thanks alot. @a-s-rose I have raised the PR for it.
I have also made a change in the vendor vector encoder to remove the default value check similar to the bug raised on TS library.

**Comment by laktech** [comment]
This consent string now fails with the following,

com.iabtcf.exceptions.InvalidRangeFieldException: start vendor id (24) is greater than endVendorId (13)

also,

com.iabtcf.exceptions.InvalidRangeFieldException: end vendor id (16403) is greater than max (686)

also,

com.iabtcf.exceptions.ByteParseException: read 3 bytes at index 79 out of bounds for buffer length 81

When checking just the OOB section, the below works fine,

```
    @Test
    public void readTcString() {
        TCString tcString = TCString.decode(base64TcString);
        System.out.println(tcString.getAllowedVendors());
        System.out.println(tcString.getDisclosedVendors());
    }
```

and prints the empty set both each field. Closing the ticket since the original issue doesn't seem to be a problem anymore.
